### ISSUE TITLE
Why choose UAV?

### ISSUE THREAD

**Issue by bdpk123** [GrokCV/HazyDet#1]
Why did you choose to use a drone for this and not a regular camera to develop the dataset? Is there any difference between a drone camera and a regular camera? What is the significance of drone aerial photography research?

**Comment by ironmanfcf** [comment]
### Question 1: Why choose to use drones instead of regular cameras to create datasets?

We chose to use drones rather than regular cameras because drones are becoming increasingly prevalent in various applications. However, there is still a significant gap in datasets captured from drone perspectives under adverse weather conditions.

For example, the rapid development of autonomous driving technology has led to the creation of large-scale detection datasets for poor weather conditions from vehicle perspective, such as [BDD100K](http://bdd-data.berkeley.edu/) and [DENSE](https://www.uni-ulm.de/en/in/driveu/projects/dense-datasets/#:~:text=We%20propose%20a%20learning-based%20approach%20for%20estimating%20dense%20depth%20from). Similarly, the RTTS in the [RESIDE](https://github.com/Boyiliee/RESIDE-dataset-link) dataset focuses on foggy weather detection using regular perspective cameras. However, datasets that include the unique features of drone images are scarce. We believe that creating such datasets is vital for advancing research and development in drone-based applications, as it can train models that are better suited to the challenge scenarios.

### Question 2: What are the differences between drone cameras and regular cameras?

Yes, there are significant differences between cameras mounted on drones and regular ground cameras, primarily due to differences in their altitude and perspectives:

- **Scale Variations**: Drone cameras capture images from varying altitudes, leading to more pronounced changes in the scale of objects within the image. This means the same object can appear in very different sizes, thereby increasing the difficulty of detection and identification.
- **Random Distribution**: The aerial perspective causes a more random distribution of objects in images, unlike the even distribution typically captured by ground cameras.
- **Higher Proportion of Small Objects**: Due to an increased field of view and greater distance from objects in drone images, there are often more small objects present. Detecting these smaller objects requires more complex algorithms.

These factors add complexity to object detection and scene understanding tasks. Dedicated models and algorithms are necessary to effectively address these challenges. For more details, you may refer to articles such as [TPH-YOLOv5](https://github.com/cv516Buaa/tph-yolov5), [CEASC](https://kkgithub.com/Cuogeihong/CEASC) and [ours](https://arxiv.org/abs/2409.19833#:~:text=Drone-based%20object%20detection%20in%20adverse%20weather%20conditions%20is%20crucial%20for).

### Question 3: What is the significance of drone aerial photography research?

As drones become increasingly integrated into daily life and multiple industries, drone aerial photography research enhances their visual intelligence. For most drones, the primary way to interact with and understand their environment is through sensors, most commonly RGB cameras. Processing and analyzing data from these cameras enables drones to autonomously perform complex tasks, such as surveillance, mapping, search and rescue, and environmental monitoring. In summary, drone aerial photography research enhances the capabilities of drones by enabling them to perceive and interpret the world more effectively, which is crucial for the continuous growth and integration of drone technology across various fields.
