### ISSUE TITLE
关于多数据输入的问题

### ISSUE THREAD

**Issue by wap1024** [GrokCV/HazyDet#2]
您好，我想请问您关于数据输入的一些问题，就是我看您在mmdet检测网络中多加了一个深度图数据的输入，然后您在处理这部分数据时使用的是mmseg的pipelines文件，请问您是为了实现双头输入就使用mmseg文件中的pipeline文件吗？非常期待您的回答，谢谢您。

**Comment by ironmanfcf** [comment]
I did not use the mmseg pipeline file.    
To add depth map data to the input data in addition to image data and instance annotations, I modified the **_load_seg_map** function in the **MMCV_LoadAnnotations** class in mmcv to get **LoadDualAnnotations** class . The original purpose of this function is to read gt segmentation map, but I rewrote it as **LoadDualAnnotations** to read depth map labels based on the path of the depth map and pass them as "gt_seg_map".    
Additionally, when performing data augmentation on images, the depth map labels should also undergo corresponding changes. For the resize and flipping operations I used, the function provides interfaces corresponding to "gt_seg_map"， which will automatically transform the depth map. For the image padding I used, I set it to 255, consistent with the default setting, and noted it in the configuration file to facilitate readers in aligning it with the **ignore_index** in the depth loss function SIRLOSS, meaning that the padded depth map should be ignored in subsequent loss calculations.   
If you need to use this framework but plan to add more data augmentation operations, you don't need to make changes to some augmentations, such as normalization and grayscale changes. However, for operations like random cropping and mosaic, since there are no reserved operations for **gt_seg_map**, you will need to rewrite them yourself. If needed, you can contact me for this part, as I have made some attempts but did not include them in this repo.

**Comment by wap1024** [comment]
Hello, thank you for your reply. I am also planning to do some multi input work (multimodal) to improve MMdet. I noticed that the work you are doing is somewhat similar, so I would like to ask for your advice. I have also considered that if there is an additional input of data, data augmentation may be necessary.

**Comment by wap1024** [comment]
您好，我想请问您下，您在输入深度图标签时也对深度图标签进行了增强操作，我看您在代码中体现在LoadDualAnnotations中，但是在您获取深度图的路径时是在train_dataloder中的data_prefix= dict(img='train/hazy_images/',seg='Depth/normalized_depth_maps/')请问您这样做的目的是保障在增强RGB图的时候，同时深度图也同步增强吗？期待您的答复。
