### ISSUE TITLE
运行报错，求助

### ISSUE THREAD

**Issue by whj-whj** [GrokCV/HazyDet#5]
尊敬的作者，您好，我在尝试运行该项目的时候，出现以下报错:FileNotFoundError: [Errno 2] No such file or directory: '/home/whj/whj/HazyDet-master/data/HazyDet/Depth/normalized_depth_maps/004054.png'
但是你们的数据集中并没有Depth这个文件夹。我想请教一下该如何解决，麻烦您了。

**Comment by YimianDai** [comment]
@ironmanfcf Check 一下

**Comment by ironmanfcf** [comment]
Our dataset serves as a comprehensive benchmark for object detectors under hazy condition, but only our algorithm utilizes depth data. In our method, depth maps can be obtained through various depth estimation models and are saved in 16-bit depth PNG format. This causes them to occupy substantial storage space, which is why we initially did not upload them to cloud storage. As mentioned earlier in the README, the depth data used for training is directly obtained through Metric3D inference. We also encourage users to explore the impact of more advanced depth estimation models (such as Metric3Dv2 and SPIdepth) on DeCoDet performance. To facilitate user access, we will upload the depth maps we used to the cloud as soon as possible.

Additionally, as mentioned in the README, the depth data used for training can be directly inferred using Metric3D. We also encourage users to explore the impact of more advanced depth estimation models on the performance of DeCoDet.

**Comment by ironmanfcf** [comment]
Our dataset serves as a comprehensive benchmark for object detectors in hazy conditions. However, only our algorithm requires depth data. In our approach, depth maps are obtained through various depth estimation models and saved in 16-bit PNG format, which leads to significant storage requirements. Consequently, we initially refrained from uploading them to cloud storage.

As mentioned in the README, the depth data used for training is **directly obtained through Metric3D inference**. We encourage users to investigate how more advanced depth estimation models, such as Metric3Dv2 and SPIdepth, might influence DeCoDet's performance. To enhance accessibility, we will **upload the depth maps we used to the cloud as soon as possible**.

**Comment by YimianDai** [comment]
有 30 个 GB，太大了，从不联网的服务器里往外挪，有点麻烦，想着又给出了教程怎么自己推理，所以前期偷懒了

会尽快补上

**Comment by ironmanfcf** [comment]
Depth data has been uploaded, please download it from Baidu Cloud Drive. For the convenience of use, I have updated the LoadDualAnnotations in HazyDet.loading.py. Please use the latest version of the code.

**Comment by agleaner** [comment]
Are the depth values ​​in your depth images in meters?
